### ISSUE TITLE
Learning Docker: Basic Tutorial

### ISSUE THREAD

**Issue by NickyDaB** [NickyDaB/RND#12]
# Goal: 
Keep track of learning docker for new comers or future reference.

# Approach:
Leave progress, what you did, articles you read, videos you watched as comments on this issue. 

# ToDo:
- [x] Install docker for desktop on Mac laptop.
- [x] Run docker `hello-world`
- [x] create a custom `Dockerfile`
- [x] create a custom image.
- [x] run the custom image.

**Comment by NickyDaB** [comment]
link to a wiki page on the repo?
